/* Monster Island: The Tidekeeper. Original classroom prototype for Alex & Victory.
   All scene meshes, mechanics, interface and audio are authored procedurally.
   Three.js is bundled locally under its MIT license. No network requests in-game. */
'use strict';
(() => {
const $=id=>document.getElementById(id), TAU=Math.PI*2, clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const dict={
en:{edition:'THE FIRST EXPEDITION',intro:'Two explorers. Two extraordinary powers.<br>A forgotten island with a secret worth finding.',chapter:'CHAPTER 01 &nbsp; / &nbsp; THE TIDEKEEPER',alexDesc:'ELECTRIC INVENTOR<br>Arc shot · Overcharge',victoryDesc:'GRAVITY MAGE<br>Stone throw · Gravity field',start:'SET SAIL AS ',menuFoot:'Solo adventure · Take turns with your friend<br>Touch controls or WASD · No downloads during play',tag:'BEYOND THE SHORE',tagSmall:'A BIG ADVENTURE STARTS SMALL.',objective:'EXPEDITION LOG',crystals:'CRYSTALS',guardian:'CAVE GUARDIAN',bossName:'THE TIDEKEEPER',moveHelp:'MOVE · WASD / ARROWS',dodge:'DODGE',controlsTip:'HOLD TO ATTACK · AUTO AIM',resume:'BACK TO ADVENTURE',retry:'TRY AGAIN',changeHero:'CHOOSE ANOTHER EXPLORER',rotate:'Turn your device sideways for a wider view',qApproach:'Follow the golden trail to the cave.',qFight:'Defeat the three-headed guardian.',qChest:'Walk to the glowing chest.',qExit:'Go through the cave to the rainforest.',welcome:'Welcome ashore! Follow the golden trail.',warning:'It is watching you. Step closer to begin.',battle:'Guardian awakened! Hold attack and keep moving.',outOfRange:'Move closer to the guardian to attack.',slam:'GET OUT OF THE RED RING!',mark:'DODGE THE MARKED GROUND!',enrage:'The guardian is faster now. Stay alert!',retreat:'Safe again. The guardian returns to its territory.',heal:'The boat is a safe place to recover.',defeated:'Guardian defeated! Your reward is by the cave.',collected:'+10 crystals! The rainforest passage is open.',idle:'GUARDING ITS TERRITORY',watch:'WATCHING YOU',fight:'STAY MOBILE',vulnerable:'GRAVITY-LOCKED',danger:'ATTACK INCOMING',calmed:'PASSAGE CLEARED',arc:'ARC SHOT',throw:'STONE THROW',overcharge:'OVERCHARGE',gravity:'GRAVITY FIELD',paused:'TAKE A BREATH',pauseTitle:'Adventure paused.',pauseText:'The island can wait. Continue when you are ready.',winEye:'CHAPTER 01 COMPLETE',winTitle:'Beyond the shore.',winText:'You found 10 crystals and opened the rainforest passage.<br>The castle and its 100-crystal treasure await in a future chapter.',loseEye:'ANOTHER TRY, EXPLORER',loseTitle:'Back to the boat.',loseText:'Watch the red warning rings. Keep moving, use your special power, and dodge just before an attack.',time:'TIME',loot:'CRYSTALS',dodges:'DODGES',full:'Fullscreen',soundOff:'Sound off',soundOn:'Sound on'},
zh:{edition:'第一次远征',intro:'两名探险家，两种超能力。<br>一座被遗忘的岛，藏着值得寻找的秘密。',chapter:'第一章 &nbsp; / &nbsp; 潮汐守卫',alexDesc:'电力发明家<br>电弧射击 · 超载电磁炮',victoryDesc:'重力魔法师<br>悬石投掷 · 重力领域',start:'出发吧，',menuFoot:'单人冒险 · 两位同学可以轮流试玩<br>触屏或键盘操作 · 游戏中无需联网加载',tag:'海岸之外',tagSmall:'大冒险，从第一步开始。',objective:'探险日志',crystals:'水晶',guardian:'洞穴守卫',bossName:'三头潮汐兽',moveHelp:'移动 · WASD / 方向键',dodge:'闪避',controlsTip:'按住持续攻击 · 自动瞄准',resume:'继续冒险',retry:'再挑战一次',changeHero:'返回选择另一名探险家',rotate:'横过来玩，能看得更清楚',qApproach:'沿着金色路标，前往海滩山洞。',qFight:'击败守在洞口的三头巨兽。',qChest:'走到洞口发光的宝箱旁。',qExit:'穿过山洞，进入雨林。',welcome:'上岸成功！沿金色路标前往洞口。',warning:'它正在盯着你。再靠近就会开始战斗。',battle:'守卫醒了！按住攻击，一边移动一边打。',outOfRange:'距离太远了，再靠近一些才能攻击。',slam:'离开红色圆圈！',mark:'躲开地上的红色标记！',enrage:'守卫变快了，小心下一次攻击！',retreat:'已离开领地。守卫回巢，生命恢复。',heal:'船边是安全区，可以恢复生命。',defeated:'守卫已被击败！去洞口领取奖励。',collected:'获得 10 颗水晶！通往雨林的道路打开了。',idle:'守护领地',watch:'正在警戒',fight:'保持移动',vulnerable:'受到重力束缚',danger:'攻击即将落下',calmed:'道路已清空',arc:'电弧射击',throw:'悬石投掷',overcharge:'超载电磁炮',gravity:'重力领域',paused:'喘口气吧',pauseTitle:'冒险已暂停',pauseText:'小岛不会跑掉。准备好了，再继续。',winEye:'第一章完成',winTitle:'走向海岸之外',winText:'你找到 10 颗水晶，打开了通往雨林的道路。<br>城堡与装有 100 颗水晶的宝箱，留待后续章节。',loseEye:'探险家，再试一次',loseTitle:'回到船边',loseText:'注意地上的红色预警。边跑边攻击，使用特殊能力，在攻击落下前闪避。',time:'用时',loot:'水晶',dodges:'闪避',soundOff:'音效已关闭',soundOn:'音效已开启'}
};
let lang='en',selected='alex',mode='menu',time=0,runTime=0,messageLeft=0,lastMessage='',shake=0,damageFlash=0,audio=null,soundEnabled=true;
try{lang=localStorage.getItem('av-language')==='zh'?'zh':'en';selected=localStorage.getItem('av-hero')==='victory'?'victory':'alex';}catch(_){}
const tr=k=>dict[lang][k]||k;
function fatal(s){$('fatal').classList.remove('hidden');$('fatal').textContent=s;}
if(!window.THREE){fatal('The 3D engine is missing. Keep the vendor folder with index.html. / 请把 vendor 文件夹与游戏文件放在一起。');return;}
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){fatal('This browser could not start WebGL. Open the game in Safari or Chrome. / 浏览器未能启动3D，请使用 Safari 或 Chrome。');return;}
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;
const scene=new THREE.Scene();scene.background=new THREE.Color('#9bcbd0');scene.fog=new THREE.Fog('#9bcbd0',48,120);
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.2,190);const cameraTarget=new THREE.Vector3();
scene.add(new THREE.HemisphereLight('#e9fbef','#4d6971',2.3));const sun=new THREE.DirectionalLight('#fff0d1',3.2);sun.position.set(-25,42,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-43;sun.shadow.camera.right=43;sun.shadow.camera.top=38;sun.shadow.camera.bottom=-45;sun.shadow.camera.near=1;sun.shadow.camera.far=115;sun.shadow.normalBias=.06;sun.shadow.bias=-.0003;scene.add(sun);sun.target.position.set(0,0,-10);scene.add(sun.target);
const matCache=new Map();function mat(c,em=0){const key=c+':'+em;if(!matCache.has(key))matCache.set(key,new THREE.MeshStandardMaterial({color:c,roughness:.85,metalness:0,flatShading:true,emissive:em?c:0,emissiveIntensity:em}));return matCache.get(key);}
const geo={box:new THREE.BoxGeometry(1,1,1),sphere:new THREE.IcosahedronGeometry(1,1),rock:new THREE.DodecahedronGeometry(1,0),cone:new THREE.ConeGeometry(1,1,6),cyl:new THREE.CylinderGeometry(1,1,1,8),gem:new THREE.OctahedronGeometry(1),ring:new THREE.RingGeometry(.86,1,64)};
function mesh(g,c,p,s,parent=scene){const m=new THREE.Mesh(g,typeof c==='string'?mat(c):c);if(p)m.position.set(...p);if(s)m.scale.set(...s);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function group(p,parent=scene){const g=new THREE.Group();g.position.set(...p);parent.add(g);return g;}
function ring(x,z,r,color,opacity=.5,parent=scene){const m=mesh(geo.ring,new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}),[x,.06,z],[r,r,r],parent);m.rotation.x=-Math.PI/2;m.castShadow=false;m.receiveShadow=false;return m;}
function cylinderBetween(a,b,r,color,parent=scene){const d=new THREE.Vector3().subVectors(b,a),m=mesh(geo.cyl,color,[0,0,0],[r,d.length(),r],parent);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return m;}
let seed=724;function rand(){seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;}const rnd=(a,b)=>a+(b-a)*rand();
const colliders=[],palmLeaves=[],floatCrystals=[],surf=[],projectiles=[],particles=[],fields=[],floatTexts=[],effects=[],telegraphs=[];const terrain=group([0,0,0]);
// Ocean and a faceted island, all generated locally.
const water=mesh(new THREE.PlaneGeometry(300,300),new THREE.MeshStandardMaterial({color:'#298d9f',roughness:.35,metalness:.12}),[0,-.68,0]);water.rotation.x=-Math.PI/2;water.receiveShadow=true;
mesh(new THREE.CylinderGeometry(39,42,3,30), '#987b55',[0,-1.75,-7],[.86,1,1.06],terrain);
mesh(new THREE.CylinderGeometry(38.9,39, .22,30),'#e9d29d',[0,-.12,-7],[.86,1,1.06],terrain);
mesh(new THREE.CylinderGeometry(24,26,.36,20),'#688e65',[0,-.19,-31],[1.12,1,.79],terrain);
// Narrow beach path and green moss islands at the sides.
for(let i=0;i<24;i++){let z=-27+i*2.25;mesh(geo.rock,'#e3c895',[Math.sin(i*.9)*.8,-.03,z],[3.7,.09,1.8],terrain);}
for(let i=0;i<19;i++){let x=i%2?-rnd(14,27):rnd(14,27),z=rnd(-32,16);mesh(geo.rock,['#94aa69','#aab67a','#819e67'][i%3],[x,.05,z],[rnd(3,6),.15,rnd(3,6)],terrain);}
for(let i=0;i<25;i++){let x=rnd(-46,46),z=rnd(24,46);const m=mesh(geo.box,new THREE.MeshBasicMaterial({color:'#c9ebe0',transparent:true,opacity:.45}),[x,-.55,z],[rnd(1,6),.02,.12]);m.castShadow=false;surf.push({m,x,z,s:rnd(.5,1.2)});}
function palm(x,z,scale=1){const g=group([x,0,z],terrain);g.scale.setScalar(scale);const lean=rnd(-.7,.7);for(let i=0;i<5;i++)mesh(geo.cyl,i%2?'#8e6c48':'#a58252',[lean*i*.15,i*.72+.35,0],[.23-i*.014,.78,.23-i*.014],g);const top=group([lean*.6,3.8,0],g);for(let i=0;i<7;i++){const a=i/7*TAU;const leaf=mesh(geo.sphere,['#386a55','#54875c','#79a05d'][i%3],[Math.cos(a)*1.28,.13,Math.sin(a)*1.28],[1.85,.13,.48],top);leaf.rotation.y=-a;leaf.rotation.z=.1;palmLeaves.push({m:leaf,z:leaf.rotation.z,k:rnd(0,6)});}for(let i=0;i<3;i++)mesh(geo.sphere,'#826143',[.3*Math.cos(i*2),3.5,.3*Math.sin(i*2)],[.2,.24,.2],g);colliders.push({x,z,r:.6*scale});}
for(const [x,z,s] of [[-11,13,1.5],[13,15,1.3],[-17,0,1.6],[18,1,1.8],[-16,-12,1.35],[17,-15,1.7],[-24,7,1.9],[24,10,1.7],[-23,-24,1.6],[22,-27,1.8],[-13,-34,1.9],[13,-34,1.7]])palm(x,z,s);
function rock(x,z,r=1,c='#6a8582',y=0){const m=mesh(geo.rock,c,[x,y+r*.5,z],[r,r*.9,r*.8],terrain);m.rotation.set(rnd(-.2,.2),rnd(0,6),rnd(-.1,.1));return m;}
for(let i=0;i<45;i++){const side=i%2?-1:1,x=side*rnd(20,32),z=rnd(-35,21),r=rnd(.7,2.7);rock(x,z,r);}
for(let i=0;i<28;i++){const x=rnd(-21,21),z=rnd(-15,22);if(Math.abs(x)<5)continue;const r=rnd(.18,.55);rock(x,z,r,'#b29d75');}
// Cave: a rock arch rather than a full interior level.
for(const side of [-1,1])for(let j=0;j<4;j++){const x=side*(6.8+j*2.0);const r=3.0+j*.6;rock(x,-28-rnd(0,3),r,'#526e6d',j*.2);rock(x,-28,2.1,'#597978',3.2+j*.4);}
for(let i=0;i<7;i++){let x=(i-3)*1.7;rock(x,-28,2.0,'#68837b',7.0-Math.abs(i-3)*.2);}
const caveDark=mesh(geo.box,new THREE.MeshBasicMaterial({color:'#153c39'}),[0,3.8,-29.5],[10,8.5,.25]);caveDark.castShadow=false;
const gate=group([0,0,-27.8]);for(let i=-2;i<=2;i++){const b=mesh(geo.box,new THREE.MeshBasicMaterial({color:'#78d4cf',transparent:true,opacity:.23,depthWrite:false}),[i*1.8,3.4,0],[.065,6.6,.08],gate);b.castShadow=false;}ring(0,-26,4.5,'#84e8e3',.45);
const gateEmblem=mesh(new THREE.TorusGeometry(.9,.05,5,36),mat('#baeddc',.3),[0,6.9,-27.45],null);gateEmblem.castShadow=false;for(let i=0;i<4;i++){const c=mesh(geo.gem,mat('#a3ffed',.55),[0,0,0],[.23,.42,.23],gateEmblem);const a=i*Math.PI/2;c.position.set(Math.sin(a)*1.2,Math.cos(a)*1.2,0);}
// Crystals on the sides make the cave readable, without implying collectable loot.
for(const [x,z] of [[-6,-25],[6,-25],[-9,-20],[9,-21]]){rock(x,z,1.0,'#647781');for(let j=0;j<3;j++){const c=mesh(geo.gem,mat(j%2?'#73cfdf':'#b3f4e8',.3),[x+(j-1)*.45,1.1+rand()*.3,z],[.3,.8+rand()*.4,.3]);c.rotation.z=(j-1)*.25;floatCrystals.push(c);}}
// Distant rainforest, volcano and castle silhouettes: landmarks only.
for(let i=0;i<34;i++){let x=rnd(-33,33),z=rnd(-65,-39),h=rnd(4,8);mesh(geo.cyl,'#4d7761',[x,h*.3,z],[.3,h*.6,.3]);mesh(geo.sphere,['#3d7566','#4c8b70','#67997b'][i%3],[x,h*.7,z],[rnd(2,4),h*.45,rnd(2,4)]);}
mesh(new THREE.ConeGeometry(15,21,9),'#728e8b',[-27,6,-68]);mesh(new THREE.ConeGeometry(4.3,5,9),'#c59b77',[-27,16.2,-68]);
for(let i=0;i<4;i++)mesh(geo.sphere,new THREE.MeshBasicMaterial({color:'#d4d4bd',transparent:true,opacity:.45}),[-27+i*.9,19+i*2,-68],[1+i*.55,1.6+i*.4,1.4+i*.4]);
const castle=group([20,4,-66]);for(const x of [-5,5]){mesh(geo.cyl,'#73968f',[x,5,0],[1.8,10,1.8],castle);mesh(geo.cone,'#57767a',[x,11,0],[2.4,3,2.4],castle);}mesh(geo.box,'#849f92',[0,4,0],[10,7,3],castle);
// Expedition boat on the beach.
const boat=group([-8,-.1,22],terrain);boat.rotation.y=-.4;mesh(new THREE.CylinderGeometry(1,1,.85,6),'#795538',[0,.3,0],[1.8,1,3.7],boat);mesh(geo.box,'#b58a52',[0,.74,0],[2.1,.22,4.7],boat);for(const s of [-1,1])mesh(geo.box,'#684a35',[s*1.13,1.03,0],[.22,.7,4.8],boat);mesh(geo.cyl,'#beaa73',[0,3.0,0],[.09,5.2,.09],boat);const sail=mesh(new THREE.PlaneGeometry(2.7,3.4),new THREE.MeshStandardMaterial({color:'#fff1cb',side:THREE.DoubleSide}),[1.18,3.47,0],null,boat);sail.rotation.y=.16;mesh(geo.box,'#174b5b',[1.2,3.45,.05],[.13,1.5,.05],boat);mesh(geo.box,'#174b5b',[1.2,3.45,.055],[1.1,.13,.05],boat);colliders.push({x:-8,z:22,r:2.7});
// Trail dots and a moving directional beacon.
const trail=[];for(let z=15;z>-24;z-=3){const t=mesh(geo.gem,mat('#f4d486',.4),[0,.16,z],[.15,.22,.15]);t.castShadow=false;trail.push(t);}
const beacon=group([0,3,-25]);mesh(geo.cone,mat('#ffde8b',.4),[0,0,0],[.5,.8,.5],beacon).rotation.z=Math.PI;const beaconRing=ring(0,-25,1.5,'#f3d387',.6);
function makeHero(type){const g=group([0,0,18]);const skin='#e5b48d',cloth=type==='alex'?'#256475':'#64558d',gold='#e8c780';const body=group([0,0,0],g);mesh(geo.cyl,cloth,[0,1.12,0],[.44,.9,.34],body);mesh(geo.box,'#203b49',[0,.78,.01],[.73,.16,.61],body);mesh(geo.box,gold,[0,.79,.34],[.16,.13,.045],body);mesh(geo.sphere,skin,[0,1.99,.02],[.36,.41,.33],body);mesh(geo.sphere,'#352d33',[0,2.17,-.03],[.38,.3,.33],body);for(const s of [-1,1])mesh(geo.sphere,'#263a41',[s*.13,2.02,.324],[.035,.045,.02],body);mesh(geo.box,skin,[0,1.79,.07],[.2,.25,.25],body);
const arms=[],legs=[];for(const s of [-1,1]){const arm=group([s*.47,1.48,0],body);mesh(geo.cyl,cloth,[0,-.25,0],[.13,.5,.13],arm);mesh(geo.sphere,skin,[0,-.55,.035],[.14,.16,.14],arm);arms.push(arm);const leg=group([s*.22,.7,0],body);mesh(geo.cyl,'#263f49',[0,-.27,0],[.14,.53,.15],leg);mesh(geo.box,'#24343b',[0,-.58,.065],[.29,.24,.48],leg);legs.push(leg);}
let focus;if(type==='alex'){mesh(geo.box,'#bdad79',[0,2.2,.31],[.68,.16,.1],body);for(const s of [-1,1])mesh(geo.cyl,mat('#90eaf0',.25),[s*.19,2.18,.36],[.12,.06,.12],body).rotation.x=Math.PI/2;mesh(geo.box,'#8c7554',[0,1.3,-.4],[.67,.64,.35],body);for(const s of [-1,1])mesh(geo.cyl,mat('#82dfdb',.7),[s*.21,1.33,-.61],[.105,.55,.105],body);focus=mesh(geo.box,'#b59b64',[0,-.56,.28],[.26,.23,.58],arms[1]);mesh(geo.cyl,mat('#a6ffff',1),[0,-.56,.65],[.12,.12,.12],arms[1]).rotation.x=Math.PI/2;
}else{mesh(new THREE.ConeGeometry(.63,.8,7),'#79659f',[0,2.55,-.04],null,body);mesh(geo.cyl,'#aa8bb6',[0,2.21,0],[.61,.08,.55],body);mesh(new THREE.ConeGeometry(.57,1.2,8,1,true),'#6c5a95',[0,.98,-.04],null,body);focus=mesh(geo.gem,mat('#d7bdff',.8),[.02,-.55,.26],[.18,.25,.18],arms[1]);for(let i=0;i<3;i++){let c=mesh(geo.rock,mat('#ada5d6',.05),[0,1,0],[.17,.23,.18],body);c.userData.orbit=i;floatCrystals.push(c);}}
const aura=ring(0,18,.8,type==='alex'?'#9df6ed':'#d5baff',.24);return{g,body,arms,legs,focus,aura,type};}
let hero=makeHero(selected);const player={x:0,z:18,hp:100,inv:0,attackCd:0,specialCd:0,dashCd:0,dashing:0,dx:0,dz:-1,attackAnim:0,steps:0};
// A large, readable three-headed animal guardian, with a shared body and distinct heads.
const bossRoot=group([0,0,-18]);const bossBody=group([0,0,0],bossRoot);const bossMats=[];function bm(c){const m=mat(c).clone();bossMats.push(m);return m;}const shell=bm('#345b65'),armor=bm('#6d9293'),dark=bm('#203d49'),gold=bm('#ceae70');
mesh(geo.sphere,shell,[0,2.65,-.5],[2.4,2.0,3.25],bossBody);mesh(geo.sphere,armor,[0,3.55,-.65],[2.1,.95,2.85],bossBody);for(let i=0;i<5;i++){mesh(geo.cone,gold,[0,4.37,-2.2+i*.78],[.36,.68,.38],bossBody);}
const bossLegs=[];for(const s of [-1,1])for(const z of [-2,1.15]){const l=group([s*1.82,2,z],bossBody);mesh(geo.cyl,shell,[0,-.8,0],[.6,2,.66],l);mesh(geo.sphere,armor,[0,-1.52,.2],[.78,.5,.94],l);for(let j=0;j<3;j++)mesh(geo.cone,'#ece3bf',[(j-1)*.33,-1.55,.91],[.14,.47,.16],l).rotation.x=Math.PI/2;bossLegs.push(l);}
const heads=[];for(let i=0;i<3;i++){const h=group([(i-1)*1.68,3.75+(i===1?.62:0),1.7],bossBody);mesh(geo.sphere,shell,[0,0,0],[.88,1.01,1.05],h);mesh(geo.sphere,armor,[0,-.24,.8],[.69,.52,.94],h);mesh(geo.box,dark,[0,-.11,1.4],[.63,.23,.46],h);mesh(geo.sphere,'#142f3a',[0,-.04,1.55],[.23,.18,.17],h);for(const s of [-1,1]){mesh(geo.cone,armor,[s*.6,.91,-.2],[.33,.98,.39],h).rotation.z=-s*.24;mesh(geo.sphere,mat('#c4fff2',.9),[s*.53,.19,.83],[.24,.14,.1],h);const brow=mesh(geo.box,gold,[s*.5,.39,.8],[.53,.12,.16],h);brow.rotation.z=s*.15;mesh(geo.cone,'#f8ebcd',[s*.42,-.47,1.21],[.13,.47,.13],h).rotation.z=Math.PI;}
mesh(geo.gem,mat('#78e5e4',.45),[0,.67,.68],[.22,.32,.11],h);heads.push(h);}
const tail=mesh(geo.cone,shell,[0,2.52,-4.6],[.46,3.7,.45],bossBody);tail.rotation.x=-Math.PI/2;const bossAura=ring(0,-18,4.0,'#edc787',.25);const boundary=ring(0,-18,15.5,'#e9c78e',.14);const boss={x:0,z:-18,hp:780,maxHp:780,state:'idle',cooldown:2,stun:0,windup:0,enraged:false,flash:0,deadTime:0,attackType:''};
// A small chest reward, not the final 100-crystal castle treasure.
const chest=group([0,0,-25]);chest.visible=false;mesh(geo.box,'#7b5138',[0,.53,0],[1.65,.9,1.15],chest);const lid=group([0,.98,-.5],chest);mesh(geo.box,'#a67945',[0,.08,.5],[1.75,.25,1.25],lid);for(const s of [-1,1])mesh(geo.box,'#dbba70',[s*.57,.6,.61],[.13,.9,.06],chest);mesh(geo.box,'#f3d18d',[0,.78,.64],[.27,.28,.08],chest);const chestGem=mesh(geo.gem,mat('#8feef5',.7),[0,1.85,0],[.33,.6,.33],chest);let chestCollected=false,crystalCount=0,stats={dodges:0,hits:0};
// Lightweight generated audio. No microphone, media, or external asset access.
function unlockAudio(){if(!audio){try{audio=new(window.AudioContext||window.webkitAudioContext)();}catch(_){}}if(audio&&audio.state==='suspended')audio.resume().catch(()=>{});}
function tone(freq,duration=.12,type='sine',vol=.05,endFreq){if(!audio||!soundEnabled)return;try{const o=audio.createOscillator(),a=audio.createGain(),now=audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,now);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,now+duration);a.gain.setValueAtTime(.0001,now);a.gain.exponentialRampToValueAtTime(vol,now+.012);a.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(a);a.connect(audio.destination);o.start();o.stop(now+duration+.02);}catch(_){}}
function chime(){[440,554,659,880].forEach((f,i)=>{setTimeout(()=>tone(f,.3,'sine',.045),i*90);});}
function message(key,seconds=3){lastMessage=key;$('message').textContent=tr(key);$('message').classList.add('show');messageLeft=seconds;}
function updateLanguage(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=tr(el.dataset.i18n));$('langBtn').textContent=lang==='en'?'中文':'EN';$('start').querySelector('span').textContent=tr('start')+(selected==='alex'?'ALEX':'VICTORY');$('attackLabel').textContent=tr(selected==='alex'?'arc':'throw');$('specialLabel').textContent=tr(selected==='alex'?'overcharge':'gravity');$('attackIcon').innerHTML='<use href="#'+(selected==='alex'?'i-bolt':'i-orbit')+'"/>';$('avatar').innerHTML=$('attackIcon').outerHTML;$('avatar').style.color=selected==='alex'?'#8fe9ee':'#d2b5ff';$('heroName').textContent=selected.toUpperCase();if(lastMessage)$('message').textContent=tr(lastMessage);refreshHUD();if(mode==='paused'||mode==='dead'||mode==='won')showOverlay(mode);try{localStorage.setItem('av-language',lang);}catch(_){} }
function selectHero(type){selected=type;document.querySelectorAll('.heroCard').forEach(b=>b.setAttribute('aria-pressed',b.dataset.hero===type?'true':'false'));if(hero){scene.remove(hero.g);scene.remove(hero.aura);}hero=makeHero(type);hero.g.position.set(player.x,0,player.z);hero.g.rotation.y=Math.PI;try{localStorage.setItem('av-hero',type);}catch(_){}updateLanguage();}
const keys=new Set(),joystick={id:null,x:0,y:0},attackPointers=new Set();let attackHeld=false;
function resetInput(){keys.clear();joystick.id=null;joystick.x=joystick.y=0;attackHeld=false;attackPointers.clear();$('joyKnob').style.transform='';}
function clearObjects(list){for(const e of list){const m=e.m||e;scene.remove(m);if(e.uniqueGeo&&m.geometry)m.geometry.dispose();if(e.uniqueMat&&m.material)m.material.dispose();}list.length=0;}
function startRun(){unlockAudio();resetInput();mode='playing';time=0;runTime=0;Object.assign(player,{x:0,z:18,hp:100,inv:0,attackCd:0,specialCd:0,dashCd:0,dashing:0,dx:0,dz:-1,attackAnim:0,steps:0});Object.assign(boss,{x:0,z:-18,hp:780,state:'idle',cooldown:2,stun:0,windup:0,enraged:false,flash:0,deadTime:0,attackType:''});bossRoot.visible=true;bossRoot.scale.setScalar(1);bossRoot.position.set(0,0,-18);bossRoot.rotation.y=0;bossBody.rotation.set(0,0,0);bossBody.position.y=0;for(const m of bossMats){m.emissive.set(0);m.emissiveIntensity=0;}chestCollected=false;crystalCount=0;chest.visible=false;lid.rotation.x=0;beacon.position.set(0,3,-25);beaconRing.position.z=-25;gate.visible=true;caveDark.visible=true;beacon.visible=true;beaconRing.visible=true;bossAura.visible=true;boundary.visible=true;stats={dodges:0,hits:0};for(const a of [projectiles,particles,fields,effects,telegraphs])clearObjects(a);floatTexts.forEach(f=>f.el.remove());floatTexts.length=0;hero.g.visible=true;hero.g.position.set(0,0,18);hero.g.rotation.y=Math.PI;camera.position.set(0,8.4,31);cameraTarget.set(0,2,9);$('menu').classList.add('hidden');$('brand').classList.add('hidden');$('overlay').classList.add('hidden');for(const id of ['hud','controls','pauseBtn'])$(id).classList.remove('hidden');message('welcome',4);refreshHUD();}
function returnMenu(){mode='menu';resetInput();for(const id of ['overlay','hud','controls','pauseBtn'])$(id).classList.add('hidden');$('menu').classList.remove('hidden');$('brand').classList.remove('hidden');bossRoot.visible=true;bossRoot.scale.setScalar(1);bossRoot.position.set(0,0,-18);bossRoot.rotation.y=.35;bossBody.position.y=0;bossRoot.rotation.z=0;hero.g.visible=true;hero.g.position.set(7,0,-5);hero.g.rotation.y=-.5;hero.aura.visible=false;bossAura.visible=true;gate.visible=true;caveDark.visible=true;chest.visible=false;beacon.visible=true;for(const a of [projectiles,particles,fields,effects,telegraphs])clearObjects(a);}
function showOverlay(kind){$('overlay').classList.remove('hidden');$('resumeBtn').classList.toggle('hidden',kind!=='paused');$('retryBtn').classList.toggle('hidden',kind==='paused');$('endEyebrow').textContent=tr(kind==='paused'?'paused':kind==='won'?'winEye':'loseEye');$('endTitle').textContent=tr(kind==='paused'?'pauseTitle':kind==='won'?'winTitle':'loseTitle');$('endText').innerHTML=tr(kind==='paused'?'pauseText':kind==='won'?'winText':'loseText');$('endStats').classList.toggle('hidden',kind==='paused');$('endStats').innerHTML='<div><b>'+Math.floor(runTime/60)+':'+String(Math.floor(runTime%60)).padStart(2,'0')+'</b><small>'+tr('time')+'</small></div><div><b>'+crystalCount+'</b><small>'+tr('loot')+'</small></div><div><b>'+stats.dodges+'</b><small>'+tr('dodges')+'</small></div>';$('endIcon').setAttribute('href',kind==='won'?'#i-gem':kind==='paused'?'#i-pause':'#i-dash');}
function pause(){if(mode==='playing'){mode='paused';resetInput();showOverlay('paused');}else if(mode==='paused'){mode='playing';resetInput();$('overlay').classList.add('hidden');}}
function end(kind){mode=kind;resetInput();showOverlay(kind);if(kind==='won')chime();else tone(150,.4,'triangle',.1,65);}
$('start').onclick=startRun;$('pickAlex').onclick=()=>selectHero('alex');$('pickVictory').onclick=()=>selectHero('victory');$('langBtn').onclick=()=>{lang=lang==='en'?'zh':'en';updateLanguage();};$('soundBtn').onclick=()=>{unlockAudio();soundEnabled=!soundEnabled;$('soundBtn').style.opacity=soundEnabled?'1':'.45';$('soundBtn').setAttribute('aria-label',tr(soundEnabled?'soundOn':'soundOff'));};$('pauseBtn').onclick=pause;$('resumeBtn').onclick=pause;$('retryBtn').onclick=startRun;$('menuBtn').onclick=returnMenu;
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&!e.repeat)pause();if(mode!=='playing')return;keys.add(e.code);if(e.code==='Space'&&!e.repeat)dodge();if(e.code==='KeyQ'&&!e.repeat)special();});addEventListener('keyup',e=>keys.delete(e.code));
addEventListener('blur',()=>{if(mode==='playing')pause();else resetInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});document.addEventListener('contextmenu',e=>e.preventDefault());
const joy=$('joystick');function joyUpdate(e){const r=joy.getBoundingClientRect(),radius=r.width*.33;let x=(e.clientX-r.left-r.width/2)/radius,y=(e.clientY-r.top-r.height/2)/radius,len=Math.hypot(x,y);if(len>1){x/=len;y/=len;}joystick.x=x;joystick.y=y;$('joyKnob').style.transform=`translate(${x*radius}px,${y*radius}px)`;}
joy.addEventListener('pointerdown',e=>{if(mode!=='playing'||joystick.id!==null)return;joystick.id=e.pointerId;joy.setPointerCapture(e.pointerId);joyUpdate(e);e.preventDefault();});joy.addEventListener('pointermove',e=>{if(e.pointerId===joystick.id)joyUpdate(e);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])joy.addEventListener(ev,e=>{if(e.pointerId===joystick.id){joystick.id=null;joystick.x=joystick.y=0;$('joyKnob').style.transform='';}});
$('attackBtn').addEventListener('pointerdown',e=>{if(mode!=='playing')return;unlockAudio();attackPointers.add(e.pointerId);attackHeld=true;$('attackBtn').setPointerCapture(e.pointerId);attack();e.preventDefault();});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('attackBtn').addEventListener(ev,e=>{attackPointers.delete(e.pointerId);attackHeld=attackPointers.size>0;});$('specialBtn').addEventListener('pointerdown',e=>{e.preventDefault();special();});$('dashBtn').addEventListener('pointerdown',e=>{e.preventDefault();dodge();});
function direction(){let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joystick.x,z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joystick.y;const len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}return{x,z,mag:Math.min(1,len)};}
function canTarget(){return boss.hp>0&&Math.hypot(player.x-boss.x,player.z-boss.z)<17.8&&Math.hypot(player.x,player.z+18)<23;}
function aggro(){if(boss.state==='idle'||boss.state==='watch'){boss.state='fight';boss.cooldown=1.8;message('battle',3.5);tone(140,.35,'triangle',.1,60);}}
function burst(x,y,z,c,count=12,scale=1){for(let i=0;i<count;i++){const m=mesh(geo.gem,mat(c,.25),[x,y,z],[.09*scale,.15*scale,.09*scale]);m.castShadow=false;particles.push({m,v:new THREE.Vector3(rnd(-3,3),rnd(1,5),rnd(-3,3)).multiplyScalar(scale),life:rnd(.4,.9),max:1});}}
function pulse(x,z,c,r=3,life=.45){const m=ring(x,z,.2,c,.8);effects.push({m,life,max:life,r,type:'ring',uniqueMat:true});}
function number(value,x,y,z,color='#fff0c4'){const el=document.createElement('span');el.className='number';el.textContent=value;el.style.color=color;$('numbers').appendChild(el);floatTexts.push({el,p:new THREE.Vector3(x,y,z),life:.9});}
function attack(){if(mode!=='playing'||player.attackCd>0)return;if(!canTarget()){if(messageLeft<.3)message('outOfRange',1.5);player.attackCd=.25;return;}aggro();player.attackAnim=.28;const isAlex=selected==='alex';player.attackCd=isAlex?.46:.76;const p=new THREE.Vector3(player.x,.95,player.z);const m=isAlex?mesh(geo.sphere,mat('#a9fbff',1),[p.x,1.4,p.z],[.19,.19,.58]):mesh(geo.rock,mat('#b3a8d1',.1),[p.x,.2,p.z],[.55,.6,.55]);m.castShadow=!isAlex;projectiles.push({m,life:2.2,speed:isAlex?31:21,damage:isAlex?23:40,type:isAlex?'bolt':'stone',lift:isAlex?0:.28,trail:0});tone(isAlex?700:260,.12,isAlex?'sawtooth':'triangle',.027,isAlex?190:510);}
function special(){if(mode!=='playing'||player.specialCd>0)return;if(!canTarget()){message('outOfRange',1.8);return;}aggro();player.attackAnim=.55;if(selected==='alex'){player.specialCd=5.5;const start=new THREE.Vector3(player.x,1.55,player.z),target=new THREE.Vector3(boss.x,3,boss.z);const points=[];for(let i=0;i<=12;i++){const v=start.clone().lerp(target,i/12);if(i>0&&i<12)v.add(new THREE.Vector3(rnd(-.5,.5),rnd(-.4,.4),rnd(-.3,.3)));points.push(v);}const g=new THREE.BufferGeometry().setFromPoints(points),line=new THREE.Line(g,new THREE.LineBasicMaterial({color:'#d3ffff',transparent:true,opacity:1}));scene.add(line);effects.push({m:line,life:.28,max:.28,type:'fade',uniqueGeo:true,uniqueMat:true});pulse(boss.x,boss.z,'#8cf9ff',5,.5);hitBoss(105);shake=.18;tone(150,.3,'sawtooth',.06,900);
}else{player.specialCd=7;boss.stun=Math.max(boss.stun,2);if(boss.windup>0){boss.windup=0;clearTelegraphs();boss.cooldown=1.4;}const g=group([boss.x,.1,boss.z]);const r=ring(0,0,5.5,'#c7a4ff',.55,g);for(let i=0;i<7;i++){const a=i/7*TAU;mesh(geo.rock,mat('#bca4e2',.15),[Math.cos(a)*3.5,.8,Math.sin(a)*3.5],[.35,.5,.35],g);}fields.push({m:g,life:2.2,tick:.4,x:boss.x,z:boss.z});hitBoss(30);burst(boss.x,2,boss.z,'#d0a9ff',18);tone(160,.45,'sine',.1,550);}}
function dodge(){if(mode!=='playing'||player.dashCd>0)return;const d=direction();if(d.mag>.1){player.dx=d.x;player.dz=d.z;}player.dashing=.26;player.inv=.58;player.dashCd=2.2;stats.dodges++;pulse(player.x,player.z,selected==='alex'?'#b1faff':'#d6b4ff',1.6,.25);tone(280,.12,'triangle',.04,620);}
function hitBoss(d){if(boss.hp<=0||mode!=='playing')return;boss.hp=Math.max(0,boss.hp-d);stats.hits++;boss.flash=.13;number(d,boss.x+rnd(-1,1),5.6,boss.z);burst(boss.x,3,boss.z+1,selected==='alex'?'#9aeef5':'#c9acff',6);if(boss.hp<=0){boss.state='dead';boss.deadTime=0;boss.windup=0;boss.stun=0;clearTelegraphs();clearObjects(fields);chest.visible=true;bossAura.visible=false;boundary.visible=false;beacon.position.set(0,3,-25);message('defeated',5);chime();burst(boss.x,3,boss.z,'#e5d295',36,1.8);}else if(!boss.enraged&&boss.hp<boss.maxHp*.45){boss.enraged=true;message('enrage',3.5);pulse(boss.x,boss.z,'#eab785',7,.7);}}
function hitPlayer(d){if(mode!=='playing'||player.inv>0)return;player.hp=Math.max(0,player.hp-d);player.inv=.75;damageFlash=.65;shake=.2;number('-'+d,player.x,2.9,player.z,'#ffaf94');tone(110,.18,'triangle',.08,65);if(player.hp<=0)end('dead');}
function clearTelegraphs(){for(const t of telegraphs){scene.remove(t.m);t.m.geometry.dispose();t.m.material.dispose();}telegraphs.length=0;}
function addTelegraph(x,z,r){const m=mesh(new THREE.CircleGeometry(r,64),new THREE.MeshBasicMaterial({color:'#ee795e',transparent:true,opacity:.25,side:THREE.DoubleSide,depthWrite:false}),[x,.12,z]);m.rotation.x=-Math.PI/2;m.castShadow=false;const outline=ring(0,0,1,'#ffbc91',.9,m);outline.rotation.x=0;outline.position.set(0,0,.01);outline.scale.set(r,r,1);telegraphs.push({m,x,z,r});}
function beginBossAttack(){boss.windup=boss.enraged?1.08:1.5;const d=Math.hypot(player.x-boss.x,player.z-boss.z);boss.attackType=d<7.8?'slam':'mark';if(boss.attackType==='slam'){addTelegraph(boss.x,boss.z,7.9);message('slam',boss.windup);}else{addTelegraph(player.x,player.z,3.8);if(boss.enraged){addTelegraph(player.x-5.6,player.z+2,2.6);addTelegraph(player.x+5.6,player.z-2,2.6);}message('mark',boss.windup);}tone(220,.2,'sine',.06,310);}
function bossAI(dt){if(boss.hp<=0){boss.deadTime+=dt;bossRoot.scale.setScalar(Math.max(0,1-boss.deadTime*.65));bossRoot.rotation.y+=dt*.5;if(boss.deadTime>1.6)bossRoot.visible=false;return;}const homeD=Math.hypot(player.x,player.z+18),d=Math.hypot(player.x-boss.x,player.z-boss.z);if((homeD>23&&boss.state==='fight')||boss.state==='return'){if(boss.state!=='return'){message('retreat',3);clearTelegraphs();boss.windup=0;clearObjects(fields);clearObjects(projectiles);boss.stun=0;}boss.state='return';let v=new THREE.Vector2(-boss.x,-18-boss.z);if(v.length()<.2){boss.x=0;boss.z=-18;boss.hp=boss.maxHp;boss.enraged=false;boss.state='idle';boss.cooldown=2;}else{v.normalize().multiplyScalar(dt*4);boss.x+=v.x;boss.z+=v.y;}}
if(boss.state==='idle'||boss.state==='watch'){if(homeD<13.5)aggro();else if(homeD<20){if(boss.state!=='watch')message('warning',3);boss.state='watch';}else boss.state='idle';}
if(boss.state==='fight'){if(boss.stun>0){boss.stun=Math.max(0,boss.stun-dt);}else if(boss.windup>0){boss.windup-=dt;telegraphs.forEach(t=>t.m.material.opacity=.22+Math.sin(time*17)*.12);if(boss.windup<=0){for(const t of telegraphs){pulse(t.x,t.z,'#f7ba79',t.r,.4);burst(t.x,.3,t.z,'#bd9c77',16,1.4);if(Math.hypot(player.x-t.x,player.z-t.z)<t.r+.25)hitPlayer(boss.enraged?23:19);}clearTelegraphs();shake=.13;boss.cooldown=boss.enraged?1.45:2.2;tone(70,.28,'triangle',.14,30);}}else{boss.cooldown-=dt;if(d>6.2){const speed=(boss.enraged?2.55:1.9)*dt;boss.x+=(player.x-boss.x)/d*speed;boss.z+=(player.z-boss.z)/d*speed;}if(boss.cooldown<=0)beginBossAttack();}}
const a=Math.atan2(player.x-boss.x,player.z-boss.z);if(boss.state!=='idle')bossRoot.rotation.y+=Math.atan2(Math.sin(a-bossRoot.rotation.y),Math.cos(a-bossRoot.rotation.y))*Math.min(1,dt*3.5);bossRoot.position.set(boss.x,0,boss.z);bossAura.position.set(boss.x,.065,boss.z);bossBody.position.y=(boss.stun>0?.65:0)+Math.sin(time*2)*.1+(boss.windup>0?Math.sin(Math.min(1.5,boss.windup)*2)*.28:0);bossBody.rotation.z=boss.stun>0?Math.sin(time*8)*.04:0;bossLegs.forEach((l,i)=>{l.rotation.x=boss.state==='fight'&&d>6.2&&!boss.windup&&boss.stun<=0?Math.sin(time*5+i*Math.PI)*.12:0;});boss.flash=Math.max(0,boss.flash-dt);for(const m of bossMats){m.emissive.set(boss.flash>0?'#c8ffff':boss.enraged?'#794730':'#000000');m.emissiveIntensity=boss.flash>0?.55:boss.enraged?.16:0;}}
function updatePlayer(dt){const d=direction();for(const k of ['inv','attackCd','specialCd','dashCd','attackAnim'])player[k]=Math.max(0,player[k]-dt);if(attackHeld||keys.has('KeyE')||keys.has('KeyJ'))attack();let x=d.x,z=d.z,speed=6.4;if(player.dashing>0){player.dashing=Math.max(0,player.dashing-dt);x=player.dx;z=player.dz;speed=23;}else if(d.mag>.1){player.dx=d.x;player.dz=d.z;}player.x+=x*speed*dt;player.z+=z*speed*dt;player.x=clamp(player.x,-21,21);player.z=clamp(player.z,-38,23);if(player.z<-25.4&&!chestCollected)player.z=-25.4;if(player.z<-26&&Math.abs(player.x)>4.0){player.x=clamp(player.x,-4,4);}for(const c of colliders){const dx=player.x-c.x,dz=player.z-c.z,len=Math.hypot(dx,dz),r=c.r+.45;if(len<r&&len>.001){player.x=c.x+dx/len*r;player.z=c.z+dz/len*r;}}if(boss.hp>0){const dx=player.x-boss.x,dz=player.z-boss.z,l=Math.hypot(dx,dz);if(l<3.15&&l>.001){player.x=boss.x+dx/l*3.15;player.z=boss.z+dz/l*3.15;}}if(player.z>16&&player.hp<100){player.hp=Math.min(100,player.hp+dt*15);if(lastMessage!=='heal'&&messageLeft<.2)message('heal',2.5);}hero.g.position.set(player.x,player.dashing>0?.3:0,player.z);hero.aura.position.set(player.x,.06,player.z);hero.aura.visible=true;let angle=hero.g.rotation.y;if(player.attackAnim>0&&canTarget())angle=Math.atan2(boss.x-player.x,boss.z-player.z);else if(d.mag>.08||player.dashing>0)angle=Math.atan2(x,z);hero.g.rotation.y+=Math.atan2(Math.sin(angle-hero.g.rotation.y),Math.cos(angle-hero.g.rotation.y))*Math.min(1,dt*15);player.steps+=dt*(d.mag>.08?12:2);hero.body.position.y=d.mag>.08?Math.abs(Math.sin(player.steps))*.08:Math.sin(time*2)*.025;hero.legs.forEach((l,i)=>l.rotation.x=d.mag>.08?Math.sin(player.steps+i*Math.PI)*.55:0);hero.arms.forEach((a,i)=>a.rotation.x=player.attackAnim>0?-1.1:(d.mag>.08?Math.sin(player.steps+i*Math.PI+Math.PI)*.4:0));hero.g.visible=player.inv>.15?Math.floor(time*15)%3!==0:true;
if(boss.hp<=0&&!chestCollected&&Math.hypot(player.x,player.z+25)<2.9){chestCollected=true;crystalCount=10;lid.rotation.x=-1.1;gate.visible=false;caveDark.visible=false;message('collected',4);beacon.position.z=-34;beaconRing.position.z=-34;burst(0,1.8,-25,'#b2faff',28,1.2);chime();}if(chestCollected&&player.z<-33)end('won');}
function updateFX(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;if(p.lift>0){p.lift-=dt;p.m.position.y+=dt*7;p.m.rotation.y+=dt*5;}else{const target=new THREE.Vector3(boss.x,2.9,boss.z+1.1),v=target.sub(p.m.position),len=v.length();v.normalize();p.m.position.addScaledVector(v,p.speed*dt);p.m.rotation.y+=dt*4;if(p.type==='bolt')p.m.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),v);if(len<2.1&&boss.hp>0){hitBoss(p.damage);p.life=0;}p.trail-=dt;if(p.trail<0){p.trail=.065;const t=mesh(geo.gem,mat(p.type==='bolt'?'#a7fbff':'#c9b2ff',.3),p.m.position.toArray(),[.075,.075,.075]);t.castShadow=false;particles.push({m:t,v:new THREE.Vector3(0,.2,0),life:.25,max:.25});}}if(p.life<=0||boss.hp<=0){scene.remove(p.m);projectiles.splice(i,1);}}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.v.y-=dt*5;p.m.position.addScaledVector(p.v,dt);p.m.rotation.x+=dt*3;p.m.scale.multiplyScalar(Math.max(.7,1-dt*1.8));if(p.life<=0){scene.remove(p.m);particles.splice(i,1);}}
for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;const a=1-e.life/e.max;if(e.type==='ring')e.m.scale.setScalar(Math.max(.01,e.r*a));e.m.material.opacity=Math.max(0,1-a)*.8;if(e.life<=0){scene.remove(e.m);if(e.uniqueGeo)e.m.geometry.dispose();if(e.uniqueMat)e.m.material.dispose();effects.splice(i,1);}}
for(let i=fields.length-1;i>=0;i--){const f=fields[i];f.life-=dt;f.tick-=dt;f.m.rotation.y+=dt*1.7;f.m.children.forEach((c,j)=>{if(j>0)c.position.y=1.4+Math.sin(time*4+j)*.8;});if(f.tick<=0){f.tick=.4;if(Math.hypot(boss.x-f.x,boss.z-f.z)<6&&boss.hp>0)hitBoss(14);}if(f.life<=0){scene.remove(f.m);fields.splice(i,1);}}
for(let i=floatTexts.length-1;i>=0;i--){const f=floatTexts[i];f.life-=dt;f.p.y+=dt*1.9;const v=f.p.clone().project(camera);f.el.style.left=(v.x*.5+.5)*innerWidth+'px';f.el.style.top=(-v.y*.5+.5)*innerHeight+'px';f.el.style.opacity=Math.min(1,f.life*3);if(f.life<=0){f.el.remove();floatTexts.splice(i,1);}}}
function refreshHUD(){$('hpValue').textContent=Math.ceil(player.hp)+' / 100';$('hpFill').style.width=player.hp+'%';$('bossHp').style.width=(boss.hp/boss.maxHp*100)+'%';$('crystals').textContent=crystalCount;$('bossPanel').classList.toggle('visible',mode==='playing'&&(boss.state!=='idle'||Math.hypot(player.x,player.z+18)<21));$('bossStatus').textContent=tr(boss.hp<=0?'calmed':boss.stun>0?'vulnerable':boss.windup>0?'danger':boss.state==='fight'?'fight':boss.state==='watch'?'watch':'idle');$('quest').textContent=tr(chestCollected?'qExit':boss.hp<=0?'qChest':boss.state==='fight'?'qFight':'qApproach');for(const [key,id] of [['dashCd','dashCd'],['specialCd','specialCd']]){const v=player[key];$(id).classList.toggle('hidden',v<=.05);$(id).textContent=Math.ceil(v);} }
function updateCamera(dt){const targetPos=new THREE.Vector3(),look=new THREE.Vector3();if(mode==='menu'){targetPos.set(19+Math.sin(time*.12)*1.5,10.2,12);look.set(1.5,3,-18);}else{const portrait=innerHeight>innerWidth;const inBattle=boss.hp>0&&(boss.state==='fight'||boss.state==='watch');const cx=player.x*.72;targetPos.set(cx,(portrait?11.3:8.5)+(inBattle?1.6:0),player.z+(portrait?18:14));look.set(player.x*.78,2.3,player.z-9.5);if(inBattle){look.x=player.x*.45+boss.x*.55;look.z=player.z*.45+boss.z*.55-1.2;look.y=3;}}
camera.position.lerp(targetPos,1-Math.exp(-dt*4));cameraTarget.lerp(look,1-Math.exp(-dt*5));camera.lookAt(cameraTarget);if(shake>0){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;} }
function tick(dt){const active=mode==='playing';if(active||mode==='menu'){time+=dt;if(active){runTime+=dt;updatePlayer(dt);if(mode==='playing')bossAI(dt);updateFX(dt);messageLeft-=dt;if(messageLeft<=0)$('message').classList.remove('show');damageFlash=Math.max(0,damageFlash-dt*2);shake=Math.max(0,shake-dt);$('damageFlash').style.opacity=damageFlash;refreshHUD();}else{heads.forEach((h,i)=>h.rotation.y=Math.sin(time*.8+i)*.12);bossBody.position.y=Math.sin(time*1.5)*.1;hero.body.position.y=Math.sin(time*2)*.04;}
for(const leaf of palmLeaves)leaf.m.rotation.z=leaf.z+Math.sin(time*1.3+leaf.k)*.05;for(const c of floatCrystals){if(c.userData.orbit!==undefined){const a=time*1.4+c.userData.orbit*TAU/3;c.position.set(Math.cos(a)*.88,1.25+Math.sin(time*2+a)*.14,Math.sin(a)*.88);}else c.rotation.y+=dt*.18;}for(const s of surf){s.m.position.z=s.z+Math.sin(time*.5+s.x)*.6;s.m.material.opacity=.18+Math.sin(time*s.s+s.x)*.13;}trail.forEach((m,i)=>{m.position.y=.17+Math.sin(time*2+i*.6)*.07;m.visible=!chestCollected;});beacon.position.y=3.1+Math.sin(time*2.5)*.25;beaconRing.material.opacity=.3+Math.sin(time*2)*.1;gateEmblem.rotation.z=time*.1;chestGem.position.y=1.85+Math.sin(time*3)*.15;chestGem.rotation.y=time;chestGem.visible=!chestCollected;heads.forEach((h,i)=>h.rotation.x=Math.sin(time*1.5+i)*.045);tail.rotation.z=Math.sin(time*2)*.08;updateCamera(dt);}}
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;tick(dt);renderer.render(scene,camera);}addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();if(mode==='playing')pause();fatal('3D graphics paused. Reload this page to restart. / 3D画面已暂停，请刷新页面。');});
// Read-only diagnostics; mutation helpers exist only with explicit ?qa=1.
const qa={snapshot:()=>({mode,selected,player:{...player},boss:{...boss},chestCollected,crystals:crystalCount,time:runTime,input:{keys:[...keys],joystick:{...joystick},attackHeld},counts:{projectiles:projectiles.length,particles:particles.length,fields:fields.length,telegraphs:telegraphs.length},renderer:{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries}})};
if(new URLSearchParams(location.search).get('qa')==='1'){qa.advance=seconds=>{for(let t=0;t<seconds;t+=1/60)tick(1/60);renderer.render(scene,camera);return qa.snapshot();};qa.position=(x,z)=>{player.x=x;player.z=z;};}
window.__islandQA=Object.freeze(qa);selectHero(selected);returnMenu();updateCamera(10);requestAnimationFrame(frame);
})();
