import test from 'node:test';import assert from 'node:assert/strict';
import {World,RULES,SHOP,cleanProgress,segmentDistance} from '../game/core.mjs';
import {TEXT,LANGS} from '../game/i18n.mjs';
const run=(w,seconds)=>{for(let i=0;i<Math.round(seconds*60);i++)w.step(1/60);};
const arena=(heroes=['alex'])=>{const w=new World({heroes,intro:false});w.begin();return w;};
test('save validation rejects NaN, infinity, negatives and excessive upgrades',()=>{assert.deepEqual(cleanProgress({coins:-99,clears:Infinity,upgrades:{power:999,health:NaN,cooldown:-1},anchorUnlocked:'true'}),{coins:0,clears:0,upgrades:{power:3,health:0,cooldown:0},anchorUnlocked:false});});
test('distant player is safe and approaching starts only within territory',()=>{const w=new World();run(w,10);assert.equal(w.s.phase,'beach');assert.equal(w.s.players[0].hp,120);w.s.players[0].z=4;w.step();assert.equal(w.s.phase,'beach');w.s.players[0].z=-4;w.step();assert.equal(w.s.phase,'intro');run(w,5);assert.equal(w.s.phase,'fight');});
test('committed battle does not reset by running back to shore',()=>{const w=arena();w.damageBoss(35,0);w.setInput(0,{z:1});run(w,2);assert.equal(w.s.phase,'fight');assert.ok(w.s.players[0].z<=3.8);assert.equal(w.s.boss.hp,925);});
test('two-player boss HP is exactly twice single at each round',()=>{for(let r=1;r<=6;r++){const a=arena(),b=arena(['alex','victory']);a.s.round=b.s.round=r;a.resetBoss();b.resetBoss();assert.equal(b.s.boss.maxHP,a.s.boss.maxHP*2);}});
test('two-stage gravity uses a persistent environmental stone',()=>{const w=arena(['victory']);const p=w.s.players[0],r=w.s.rocks[2];p.x=r.x;p.z=r.z;assert.equal(w.command(0,'attack'),true);assert.equal(r.status,'lifting');assert.equal(p.holding,r.id);run(w,.5);assert.equal(r.status,'held');const before=w.s.boss.hp;assert.equal(w.command(0,'attack'),true);assert.equal(r.status,'flying');run(w,2);assert.ok(w.s.boss.hp<before);assert.equal(p.holding,null);assert.equal(r.status,'cooldown');run(w,4);assert.equal(r.status,'ground');});
test('a rock is atomically reserved and cannot be picked up by two players',()=>{const w=arena(['victory','victory']);w.s.rocks=w.s.rocks.slice(0,1);const r=w.s.rocks[0];for(const p of w.s.players){p.x=r.x;p.z=r.z;}assert.ok(w.command(0,'attack'));assert.equal(w.command(1,'attack'),false);assert.equal(r.owner,0);});
test('telegraphed attack does not apply early damage, then hits',()=>{const w=arena();const p=w.s.players[0];p.x=5;p.z=-10;w.prepareBossAttack();const hp=p.hp;run(w,.8);assert.equal(p.hp,hp);run(w,.75);assert.ok(p.hp<hp);});
test('boss cycles through four attack families including ranged projectiles',()=>{const w=arena(['alex','victory']);const types=[];for(let i=0;i<4;i++){w.prepareBossAttack();types.push(w.s.boss.attack);if(i===1){w.releaseBossAttack();assert.equal(w.s.shots.length,10);} }assert.deepEqual(types,['stomp','breath','charge','roar']);});
test('heavy ability is gated, reduces damage and blocks knockback',()=>{const w=arena();const p=w.s.players[0];assert.equal(w.command(0,'anchor'),false);p.anchorUnlocked=true;assert.equal(w.command(0,'anchor'),true);const x=p.x;w.damagePlayer(p,40,{x:5,z:3});assert.equal(p.hp,102);assert.equal(p.x,x);w.setInput(0,{x:1});const before=p.x;run(w,.5);assert.ok(p.x-before<2);});
test('dash has real invulnerability and cooldown',()=>{const w=arena();const p=w.s.players[0];w.command(0,'dash');w.damagePlayer(p,40);assert.equal(p.hp,120);assert.equal(w.command(0,'dash'),false);run(w,.7);w.damagePlayer(p,40);assert.equal(p.hp,80);});
test('gravity interrupts windup and cannot go negative',()=>{const w=arena(['victory']);w.prepareBossAttack();assert.ok(w.s.boss.windup>0);w.command(0,'special');assert.equal(w.s.boss.windup,0);assert.equal(w.s.boss.stun,2);assert.equal(w.command(0,'special'),false);});
test('reward, purchase and growth loop applies exactly once',()=>{const w=arena();w.damageBoss(960,0);assert.equal(w.s.phase,'loot');assert.ok(w.grant());assert.equal(w.grant(),false);const p=w.s.players[0];assert.equal(p.coins,12);assert.ok(p.anchorUnlocked);assert.ok(w.command(0,'buy:power'));assert.equal(p.coins,7);assert.ok(w.command(0,'buy:power'));assert.equal(p.coins,0);assert.equal(w.command(0,'buy:power'),false);assert.equal(p.upgrades.power,2);w.command(0,'rematch');assert.equal(w.s.round,2);assert.ok(w.s.boss.maxHP>960);assert.equal(w.s.rewarded,false);});
test('invalid input cannot teleport, set HP, exceed speed, or poison state',()=>{const w=arena();w.setInput(0,{x:Infinity,z:NaN,hp:9999});w.step();assert.ok(Number.isFinite(w.s.players[0].x));assert.equal(w.s.players[0].hp,120);w.setInput(0,{x:100,z:-100});const input=w.input[0];assert.ok(Math.hypot(input.x,input.z)<=1.000001);});
test('pause freezes state, flushes input and requires both clients connected',()=>{const w=arena(['alex','victory']);w.setInput(0,{x:1,attack:true});w.setConnected(1,false);const before=w.snapshot();run(w,5);assert.deepEqual(w.snapshot(),before);assert.equal(w.pause(false),false);w.setConnected(1,true);assert.equal(w.pause(false),true);assert.deepEqual(w.input,{});});
test('all-player defeat ends battle, single downed partner does not',()=>{const w=arena(['alex','victory']);w.damagePlayer(w.s.players[0],999);assert.equal(w.s.phase,'fight');w.damagePlayer(w.s.players[1],999);assert.equal(w.s.phase,'dead');});
test('swept collision catches fast projectile crossing a target',()=>{assert.equal(segmentDistance({x:0,z:0},{x:-10,z:0},{x:10,z:0}),0);});
test('every game translation key has three nonempty language values',()=>{for(const [key,values] of Object.entries(TEXT)){assert.equal(values.length,LANGS.length,key);for(const text of values)assert.equal(typeof text,'string',key);assert.ok(values.every(v=>v.length>0),key);}});
for(const hero of ['alex','victory'])test(hero+' completes a rules-driven fight and claims the chest without damage shortcuts',()=>{const w=arena([hero]);let steps=0;for(;steps<60*110&&w.s.phase==='fight';steps++){
 const p=w.s.players[0],b=w.s.boss;const a=w.s.t*.52,x=Math.sin(a)*11,z=-12+Math.cos(a)*9;
 w.setInput(0,{x:x-p.x,z:z-p.z,attack:hero==='alex'});
 if(hero==='victory')w.command(0,'attack');if(p.specialCD<=0)w.command(0,'special');if(b.windup>0&&b.windup<.26&&p.dashCD<=0)w.command(0,'dash');w.step();
 }assert.equal(w.s.phase,'loot',JSON.stringify({hero,time:w.s.t,hp:w.s.players[0].hp,boss:w.s.boss.hp}));
 for(let i=0;i<60*15&&w.s.phase==='loot';i++){const p=w.s.players[0];w.setInput(0,{x:-p.x,z:-24.5-p.z});w.step();}
 assert.equal(w.s.phase,'shop');assert.equal(w.s.players[0].coins,12);});
